### ISSUE TITLE
Bug: Bad positions don't revert

### ISSUE THREAD

**Issue by nqeron** [nqeron/TakAnalysis#1]
Using a go / navigate to a bad position leaves the marker with the bad data on (or in the undo stack?), causing potential crashes, e.g.:

c5-
Movement error:  illegal slide
d2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xabe4a]

goroutine 1 [running]:
panic(0x183080, 0xc82000c0a0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/nelhage/taktician/tak.alloc(0x0, 0x202318)
    /Users/NoahSFields/Documents/go_workspace/external/src/github.com/nelhage/taktician/tak/alloc.go:60 +0x2a
github.com/nelhage/taktician/tak.(_Position).MovePreallocated(0x0, 0xc82004dea8, 0x0, 0x0, 0x0, 0x0)
    /Users/NoahSFields/Documents/go_workspace/external/src/github.com/nelhage/taktician/tak/move.go:90 +0x58
github.com/nelhage/taktician/tak.(_Position).Move(0x0, 0xc82004dea8, 0x3, 0x0, 0x0)
    /Users/NoahSFields/Documents/go_workspace/external/src/github.com/nelhage/taktician/tak/move.go:85 +0x40
main.main()
    /Users/NoahSFields/Documents/go_workspace/internal/src/github.com/nqeron/TakAnalysis/main.go:235 +0x1705

**Comment by nqeron** [comment]
Fixed
